name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "*/10 13 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CREDLY_USER: "casper-dijkstra"
